// Student Name: Abdelrahman Zahran.
// Student Number: 150120998.
/** Class Item: consists of the ids of the employees 
 * + number of Items produced by the employees in the factory. */

public class Item {
	// Data field id keeps the id of the Item object created.
	private int id;
	// Static data field numberOfItems keeps the number of item objects created.
	public static int numberOfItems;
	
	// An Item object represents an item generated by the employees working for the factory.
	public Item(int id) {
		this.id = id;
		numberOfItems++;
	}
}
// This Program uses End-of-line Style.